services:
  - type: web
    name: tcc-dashboard
    runtime: docker
    region: ohio
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: Dashboard
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:BWskfY9YT036Qrio94ikbH83MZbC7nAiAKxgbd0vZ+g=
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: https://tcc-dashboard.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: ep-proud-heart-acvmtl8f-pooler.sa-east-1.aws.neon.tech
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: neondb
      - key: DB_USERNAME
        value: neondb_owner
      - key: DB_PASSWORD
        value: npg_VvXhG1akp7Zd
      - key: DB_SSLMODE
        value: require
      - key: CACHE_STORE
        value: file
      - key: SESSION_DRIVER
        value: cookie
      - key: LOG_LEVEL
        value: info
